sh sound-download.sh act data/sound/149.mp3
sh sound-download.sh actor data/sound/150.mp3
sh sound-download.sh alone data/sound/151.mp3
sh sound-download.sh always data/sound/152.mp3
sh sound-download.sh teach data/sound/153.mp3
sh sound-download.sh burn data/sound/154.mp3
sh sound-download.sh green data/sound/155.mp3
sh sound-download.sh blue data/sound/156.mp3
sh sound-download.sh sky data/sound/157.mp3
sh sound-download.sh astronaut data/sound/158.mp3
sh sound-download.sh space data/sound/159.mp3
sh sound-download.sh album data/sound/160.mp3
sh sound-download.sh grape data/sound/161.mp3
sh sound-download.sh apple data/sound/162.mp3
sh sound-download.sh able data/sound/163.mp3
sh sound-download.sh about data/sound/164.mp3
sh sound-download.sh above data/sound/165.mp3
sh sound-download.sh ache data/sound/166.mp3
sh sound-download.sh across data/sound/167.mp3
sh sound-download.sh ambulance data/sound/168.mp3
sh sound-download.sh clothes data/sound/169.mp3
sh sound-download.sh jeans data/sound/170.mp3
sh sound-download.sh animal data/sound/171.mp3
sh sound-download.sh cow data/sound/172.mp3
sh sound-download.sh clean data/sound/173.mp3
sh sound-download.sh dirty data/sound/174.mp3
sh sound-download.sh cheap data/sound/175.mp3
sh sound-download.sh expensive data/sound/176.mp3
sh sound-download.sh dry data/sound/177.mp3
sh sound-download.sh wet data/sound/178.mp3
sh sound-download.sh cartoon data/sound/179.mp3
sh sound-download.sh draw data/sound/180.mp3
sh sound-download.sh breakfast data/sound/181.mp3
sh sound-download.sh eat data/sound/182.mp3
sh sound-download.sh boil data/sound/183.mp3
sh sound-download.sh borrow data/sound/184.mp3
sh sound-download.sh book data/sound/185.mp3
sh sound-download.sh inside data/sound/186.mp3
sh sound-download.sh outside data/sound/187.mp3
sh sound-download.sh angry data/sound/188.mp3
sh sound-download.sh club data/sound/189.mp3
sh sound-download.sh join data/sound/190.mp3
sh sound-download.sh call data/sound/191.mp3
sh sound-download.sh phone data/sound/192.mp3
sh sound-download.sh easy data/sound/193.mp3
sh sound-download.sh difficult data/sound/194.mp3
sh sound-download.sh morning data/sound/195.mp3
sh sound-download.sh night data/sound/196.mp3
sh sound-download.sh end data/sound/197.mp3
sh sound-download.sh begin data/sound/198.mp3
sh sound-download.sh happy data/sound/199.mp3
sh sound-download.sh bird data/sound/200.mp3
sh sound-download.sh rabbit data/sound/201.mp3
sh sound-download.sh noodle data/sound/202.mp3
sh sound-download.sh address data/sound/203.mp3
sh sound-download.sh afford data/sound/204.mp3
sh sound-download.sh afraid data/sound/205.mp3
sh sound-download.sh again data/sound/206.mp3
sh sound-download.sh age data/sound/207.mp3
sh sound-download.sh ankle data/sound/208.mp3
sh sound-download.sh left data/sound/209.mp3
sh sound-download.sh radio data/sound/210.mp3
sh sound-download.sh big data/sound/211.mp3
sh sound-download.sh salt data/sound/212.mp3
sh sound-download.sh listen data/sound/213.mp3
sh sound-download.sh math data/sound/214.mp3
sh sound-download.sh make data/sound/215.mp3
sh sound-download.sh cake data/sound/216.mp3
sh sound-download.sh kite data/sound/217.mp3
sh sound-download.sh fly data/sound/218.mp3
sh sound-download.sh guitar data/sound/219.mp3
sh sound-download.sh room data/sound/220.mp3
sh sound-download.sh invent data/sound/221.mp3
sh sound-download.sh right data/sound/222.mp3
sh sound-download.sh small data/sound/223.mp3
sh sound-download.sh music data/sound/224.mp3
sh sound-download.sh ago data/sound/225.mp3
sh sound-download.sh ahead data/sound/226.mp3
sh sound-download.sh almost data/sound/227.mp3
sh sound-download.sh already data/sound/228.mp3
sh sound-download.sh before data/sound/229.mp3
sh sound-download.sh boring data/sound/230.mp3
sh sound-download.sh safe data/sound/231.mp3
sh sound-download.sh area data/sound/232.mp3
sh sound-download.sh food data/sound/233.mp3
sh sound-download.sh body data/sound/234.mp3
sh sound-download.sh leg data/sound/235.mp3
sh sound-download.sh sun data/sound/236.mp3
sh sound-download.sh away data/sound/237.mp3
sh sound-download.sh baby data/sound/238.mp3
sh sound-download.sh dish data/sound/239.mp3
sh sound-download.sh band data/sound/240.mp3
sh sound-download.sh movie data/sound/241.mp3
sh sound-download.sh foot data/sound/242.mp3
sh sound-download.sh dangerous data/sound/243.mp3
sh sound-download.sh autumn data/sound/244.mp3
sh sound-download.sh sunglasses data/sound/245.mp3
sh sound-download.sh delicious data/sound/246.mp3
sh sound-download.sh bamboo data/sound/247.mp3
sh sound-download.sh after data/sound/248.mp3
sh sound-download.sh save data/sound/249.mp3
sh sound-download.sh money data/sound/250.mp3
sh sound-download.sh brush data/sound/251.mp3
sh sound-download.sh necklace data/sound/252.mp3
sh sound-download.sh bark data/sound/253.mp3
sh sound-download.sh coat data/sound/254.mp3
sh sound-download.sh jacket data/sound/255.mp3
sh sound-download.sh seafood data/sound/256.mp3
sh sound-download.sh pretty data/sound/257.mp3
sh sound-download.sh get data/sound/258.mp3
sh sound-download.sh lose data/sound/259.mp3
sh sound-download.sh smart data/sound/260.mp3
sh sound-download.sh doctor data/sound/261.mp3
sh sound-download.sh choose data/sound/262.mp3
sh sound-download.sh dentist data/sound/263.mp3
sh sound-download.sh bar data/sound/264.mp3
sh sound-download.sh barber data/sound/265.mp3
sh sound-download.sh ring data/sound/266.mp3
sh sound-download.sh basket data/sound/267.mp3
sh sound-download.sh bath data/sound/268.mp3
sh sound-download.sh day data/sound/269.mp3
sh sound-download.sh become data/sound/270.mp3
sh sound-download.sh minute data/sound/271.mp3
sh sound-download.sh month data/sound/272.mp3
sh sound-download.sh king data/sound/273.mp3
sh sound-download.sh pull data/sound/274.mp3
sh sound-download.sh soldier data/sound/275.mp3
sh sound-download.sh princess data/sound/276.mp3
sh sound-download.sh push data/sound/277.mp3
sh sound-download.sh bean data/sound/278.mp3
sh sound-download.sh different data/sound/279.mp3
sh sound-download.sh subject data/sound/280.mp3
sh sound-download.sh science data/sound/281.mp3
sh sound-download.sh flower data/sound/282.mp3
sh sound-download.sh prince data/sound/283.mp3
sh sound-download.sh same data/sound/284.mp3
sh sound-download.sh crown data/sound/285.mp3
sh sound-download.sh beat data/sound/286.mp3
sh sound-download.sh because data/sound/287.mp3
sh sound-download.sh hour data/sound/288.mp3
sh sound-download.sh fix data/sound/289.mp3
sh sound-download.sh useful data/sound/290.mp3
sh sound-download.sh box data/sound/291.mp3
sh sound-download.sh hobby data/sound/292.mp3
sh sound-download.sh fresh data/sound/293.mp3
sh sound-download.sh air data/sound/294.mp3
sh sound-download.sh open data/sound/295.mp3
sh sound-download.sh cloudy data/sound/296.mp3
sh sound-download.sh purple data/sound/297.mp3
sh sound-download.sh vegetable data/sound/298.mp3
sh sound-download.sh use data/sound/299.mp3
sh sound-download.sh favorite data/sound/300.mp3
sh sound-download.sh help data/sound/301.mp3
sh sound-download.sh bed data/sound/302.mp3
sh sound-download.sh bell data/sound/303.mp3
sh sound-download.sh between data/sound/304.mp3
sh sound-download.sh board data/sound/305.mp3
sh sound-download.sh boat data/sound/306.mp3
sh sound-download.sh bone data/sound/307.mp3
sh sound-download.sh ride data/sound/308.mp3
sh sound-download.sh art data/sound/309.mp3
sh sound-download.sh write data/sound/310.mp3
sh sound-download.sh buy data/sound/311.mp3
sh sound-download.sh brain data/sound/312.mp3
sh sound-download.sh sing data/sound/313.mp3
sh sound-download.sh play data/sound/314.mp3
sh sound-download.sh break data/sound/315.mp3
sh sound-download.sh plant data/sound/316.mp3
sh sound-download.sh bridge data/sound/317.mp3
sh sound-download.sh sorry data/sound/318.mp3
sh sound-download.sh future data/sound/319.mp3
sh sound-download.sh wash data/sound/320.mp3
sh sound-download.sh queen data/sound/321.mp3
sh sound-download.sh card data/sound/322.mp3
sh sound-download.sh ticket data/sound/323.mp3
sh sound-download.sh brand data/sound/324.mp3
sh sound-download.sh game data/sound/325.mp3
sh sound-download.sh breathe data/sound/326.mp3
sh sound-download.sh Thank data/sound/327.mp3
sh sound-download.sh artist data/sound/328.mp3
sh sound-download.sh watch data/sound/329.mp3
sh sound-download.sh visit data/sound/330.mp3
sh sound-download.sh grandparents data/sound/331.mp3
sh sound-download.sh hungry data/sound/332.mp3
sh sound-download.sh full data/sound/333.mp3
sh sound-download.sh thick data/sound/334.mp3
sh sound-download.sh thin data/sound/335.mp3
sh sound-download.sh family data/sound/336.mp3
sh sound-download.sh cousin data/sound/337.mp3
sh sound-download.sh mix data/sound/338.mp3
sh sound-download.sh season data/sound/339.mp3
sh sound-download.sh fall data/sound/340.mp3
sh sound-download.sh sport data/sound/341.mp3
sh sound-download.sh football data/sound/342.mp3
sh sound-download.sh carry data/sound/343.mp3
sh sound-download.sh nurse data/sound/344.mp3
sh sound-download.sh camera data/sound/345.mp3
sh sound-download.sh dead data/sound/346.mp3
sh sound-download.sh business data/sound/347.mp3
sh sound-download.sh butter data/sound/348.mp3
sh sound-download.sh plane data/sound/349.mp3
sh sound-download.sh character data/sound/350.mp3
sh sound-download.sh strong data/sound/351.mp3
sh sound-download.sh weak data/sound/352.mp3
sh sound-download.sh go data/sound/353.mp3
sh sound-download.sh pilot data/sound/354.mp3
sh sound-download.sh chance data/sound/355.mp3
sh sound-download.sh bake data/sound/356.mp3
sh sound-download.sh congratulate data/sound/357.mp3
sh sound-download.sh fast data/sound/358.mp3
sh sound-download.sh warm data/sound/359.mp3
sh sound-download.sh stretch data/sound/360.mp3
sh sound-download.sh bye data/sound/361.mp3
sh sound-download.sh care data/sound/362.mp3
sh sound-download.sh center data/sound/363.mp3
sh sound-download.sh bring data/sound/364.mp3
sh sound-download.sh church data/sound/365.mp3
sh sound-download.sh check data/sound/366.mp3
sh sound-download.sh stop data/sound/367.mp3
sh sound-download.sh cartoon data/sound/368.mp3
sh sound-download.sh date data/sound/369.mp3
sh sound-download.sh drive data/sound/370.mp3
sh sound-download.sh brave data/sound/371.mp3
sh sound-download.sh brown data/sound/372.mp3
sh sound-download.sh aunt data/sound/373.mp3
sh sound-download.sh butterfly data/sound/374.mp3
sh sound-download.sh chew data/sound/375.mp3
sh sound-download.sh introduce data/sound/376.mp3
sh sound-download.sh jump data/sound/377.mp3
sh sound-download.sh off data/sound/378.mp3
sh sound-download.sh homework data/sound/379.mp3
sh sound-download.sh surf data/sound/380.mp3
sh sound-download.sh enjoy data/sound/381.mp3
sh sound-download.sh party data/sound/382.mp3
sh sound-download.sh corner data/sound/383.mp3
sh sound-download.sh curly data/sound/384.mp3
sh sound-download.sh curtain data/sound/385.mp3
sh sound-download.sh bright data/sound/386.mp3
sh sound-download.sh deep data/sound/387.mp3
sh sound-download.sh scary data/sound/388.mp3
sh sound-download.sh country data/sound/389.mp3
sh sound-download.sh doll data/sound/390.mp3
sh sound-download.sh busy data/sound/391.mp3
sh sound-download.sh free data/sound/392.mp3
sh sound-download.sh early data/sound/393.mp3
sh sound-download.sh late data/sound/394.mp3
sh sound-download.sh round data/sound/395.mp3
sh sound-download.sh live data/sound/396.mp3
sh sound-download.sh back data/sound/397.mp3
sh sound-download.sh ball data/sound/398.mp3
sh sound-download.sh circle data/sound/399.mp3
sh sound-download.sh ready data/sound/400.mp3
sh sound-download.sh newspaper data/sound/401.mp3
sh sound-download.sh read data/sound/402.mp3
sh sound-download.sh whole data/sound/403.mp3
sh sound-download.sh noon data/sound/404.mp3
sh sound-download.sh wish data/sound/405.mp3
sh sound-download.sh world data/sound/406.mp3
sh sound-download.sh worry data/sound/407.mp3
sh sound-download.sh together data/sound/408.mp3
sh sound-download.sh poor data/sound/409.mp3
sh sound-download.sh sweet data/sound/410.mp3
sh sound-download.sh laugh data/sound/411.mp3
sh sound-download.sh duck data/sound/412.mp3
sh sound-download.sh candy data/sound/413.mp3
sh sound-download.sh spicy data/sound/414.mp3
sh sound-download.sh look data/sound/415.mp3
sh sound-download.sh fan data/sound/416.mp3
sh sound-download.sh upset data/sound/417.mp3
sh sound-download.sh win data/sound/418.mp3
sh sound-download.sh pay data/sound/419.mp3
sh sound-download.sh child data/sound/420.mp3
sh sound-download.sh tooth data/sound/421.mp3
sh sound-download.sh drop data/sound/422.mp3
sh sound-download.sh factory data/sound/423.mp3
sh sound-download.sh rich data/sound/424.mp3
sh sound-download.sh excuse data/sound/425.mp3
sh sound-download.sh errand data/sound/426.mp3
sh sound-download.sh famous data/sound/427.mp3
sh sound-download.sh behind data/sound/428.mp3
sh sound-download.sh red data/sound/429.mp3
sh sound-download.sh blood data/sound/430.mp3
sh sound-download.sh block data/sound/431.mp3
sh sound-download.sh bad data/sound/432.mp3
sh sound-download.sh poor data/sound/434.mp3
sh sound-download.sh sweet data/sound/435.mp3
sh sound-download.sh laugh data/sound/436.mp3
sh sound-download.sh duck data/sound/437.mp3
sh sound-download.sh candy data/sound/438.mp3
sh sound-download.sh spicy data/sound/439.mp3
sh sound-download.sh look data/sound/440.mp3
sh sound-download.sh fan data/sound/441.mp3
sh sound-download.sh upset data/sound/442.mp3
sh sound-download.sh win data/sound/443.mp3
sh sound-download.sh pay data/sound/444.mp3
sh sound-download.sh child data/sound/445.mp3
sh sound-download.sh tooth data/sound/446.mp3
sh sound-download.sh drop data/sound/447.mp3
sh sound-download.sh factory data/sound/448.mp3
sh sound-download.sh rich data/sound/449.mp3
sh sound-download.sh excuse data/sound/450.mp3
sh sound-download.sh errand data/sound/451.mp3
sh sound-download.sh famous data/sound/452.mp3
sh sound-download.sh behind data/sound/453.mp3
sh sound-download.sh fix data/sound/455.mp3
sh sound-download.sh useful data/sound/456.mp3
sh sound-download.sh box data/sound/457.mp3
sh sound-download.sh hobby data/sound/458.mp3
sh sound-download.sh fresh data/sound/459.mp3
sh sound-download.sh air data/sound/460.mp3
sh sound-download.sh open data/sound/461.mp3
sh sound-download.sh cloudy data/sound/462.mp3
sh sound-download.sh purple data/sound/463.mp3
sh sound-download.sh vegetable data/sound/464.mp3
sh sound-download.sh use data/sound/465.mp3
sh sound-download.sh favorite data/sound/466.mp3
sh sound-download.sh help data/sound/467.mp3
sh sound-download.sh bed data/sound/468.mp3
sh sound-download.sh bell data/sound/469.mp3
sh sound-download.sh between data/sound/470.mp3
sh sound-download.sh board data/sound/471.mp3
sh sound-download.sh boat data/sound/472.mp3
sh sound-download.sh bone data/sound/473.mp3
sh sound-download.sh ride data/sound/474.mp3
sh sound-download.sh before data/sound/476.mp3
sh sound-download.sh boring data/sound/477.mp3
sh sound-download.sh safe data/sound/478.mp3
sh sound-download.sh area data/sound/479.mp3
sh sound-download.sh food data/sound/480.mp3
sh sound-download.sh body data/sound/481.mp3
sh sound-download.sh leg data/sound/482.mp3
sh sound-download.sh sun data/sound/483.mp3
sh sound-download.sh away data/sound/484.mp3
sh sound-download.sh baby data/sound/485.mp3
sh sound-download.sh dish data/sound/486.mp3
sh sound-download.sh band data/sound/487.mp3
sh sound-download.sh movie data/sound/488.mp3
sh sound-download.sh foot data/sound/489.mp3
sh sound-download.sh dangerous data/sound/490.mp3
sh sound-download.sh autumn data/sound/491.mp3
sh sound-download.sh sunglasses data/sound/492.mp3
sh sound-download.sh delicious data/sound/493.mp3
sh sound-download.sh bamboo data/sound/494.mp3
sh sound-download.sh after data/sound/495.mp3
sh sound-download.sh alphabet data/sound/497.mp3
sh sound-download.sh yeah data/sound/498.mp3
sh sound-download.sh hey data/sound/499.mp3
sh sound-download.sh club data/sound/501.mp3
sh sound-download.sh join data/sound/502.mp3
sh sound-download.sh call data/sound/503.mp3
sh sound-download.sh phone data/sound/504.mp3
sh sound-download.sh easy data/sound/505.mp3
sh sound-download.sh difficult data/sound/506.mp3
sh sound-download.sh morning data/sound/507.mp3
sh sound-download.sh night data/sound/508.mp3
sh sound-download.sh end data/sound/509.mp3
sh sound-download.sh begin data/sound/510.mp3
sh sound-download.sh happy data/sound/511.mp3
sh sound-download.sh bird data/sound/512.mp3
sh sound-download.sh rabbit data/sound/513.mp3
sh sound-download.sh noodle data/sound/514.mp3
sh sound-download.sh address data/sound/515.mp3
sh sound-download.sh afford data/sound/516.mp3
sh sound-download.sh afraid data/sound/517.mp3
sh sound-download.sh again data/sound/518.mp3
sh sound-download.sh age data/sound/519.mp3
sh sound-download.sh ankle data/sound/520.mp3
sh sound-download.sh save data/sound/522.mp3
sh sound-download.sh money data/sound/523.mp3
sh sound-download.sh brush data/sound/524.mp3
sh sound-download.sh necklace data/sound/525.mp3
sh sound-download.sh bark data/sound/526.mp3
sh sound-download.sh coat data/sound/527.mp3
sh sound-download.sh jacket data/sound/528.mp3
sh sound-download.sh seafood data/sound/529.mp3
sh sound-download.sh pretty data/sound/530.mp3
sh sound-download.sh get data/sound/531.mp3
sh sound-download.sh lose data/sound/532.mp3
sh sound-download.sh smart data/sound/533.mp3
sh sound-download.sh doctor data/sound/534.mp3
sh sound-download.sh choose data/sound/535.mp3
sh sound-download.sh dentist data/sound/536.mp3
sh sound-download.sh bar data/sound/537.mp3
sh sound-download.sh barber data/sound/538.mp3
sh sound-download.sh ring data/sound/539.mp3
sh sound-download.sh basket data/sound/540.mp3
sh sound-download.sh bath data/sound/541.mp3
sh sound-download.sh act data/sound/543.mp3
sh sound-download.sh actor data/sound/544.mp3
sh sound-download.sh alone data/sound/545.mp3
sh sound-download.sh always data/sound/546.mp3
sh sound-download.sh teach data/sound/547.mp3
sh sound-download.sh burn data/sound/548.mp3
sh sound-download.sh green data/sound/549.mp3
sh sound-download.sh blue data/sound/550.mp3
sh sound-download.sh sky data/sound/551.mp3
sh sound-download.sh astronaut data/sound/552.mp3
sh sound-download.sh space data/sound/553.mp3
sh sound-download.sh album data/sound/554.mp3
sh sound-download.sh grape data/sound/555.mp3
sh sound-download.sh apple data/sound/556.mp3
sh sound-download.sh able data/sound/557.mp3
sh sound-download.sh about data/sound/558.mp3
sh sound-download.sh above data/sound/559.mp3
sh sound-download.sh ache data/sound/560.mp3
sh sound-download.sh across data/sound/561.mp3
sh sound-download.sh ambulance data/sound/562.mp3
sh sound-download.sh day data/sound/564.mp3
sh sound-download.sh become data/sound/565.mp3
sh sound-download.sh minute data/sound/566.mp3
sh sound-download.sh month data/sound/567.mp3
sh sound-download.sh king data/sound/568.mp3
sh sound-download.sh pull data/sound/569.mp3
sh sound-download.sh soldier data/sound/570.mp3
sh sound-download.sh princess data/sound/571.mp3
sh sound-download.sh push data/sound/572.mp3
sh sound-download.sh bean data/sound/573.mp3
sh sound-download.sh different data/sound/574.mp3
sh sound-download.sh subject data/sound/575.mp3
sh sound-download.sh science data/sound/576.mp3
sh sound-download.sh flower data/sound/577.mp3
sh sound-download.sh prince data/sound/578.mp3
sh sound-download.sh same data/sound/579.mp3
sh sound-download.sh crown data/sound/580.mp3
sh sound-download.sh beat data/sound/581.mp3
sh sound-download.sh because data/sound/582.mp3
sh sound-download.sh hour data/sound/583.mp3
sh sound-download.sh country data/sound/585.mp3
sh sound-download.sh doll data/sound/586.mp3
sh sound-download.sh busy data/sound/587.mp3
sh sound-download.sh free data/sound/588.mp3
sh sound-download.sh early data/sound/589.mp3
sh sound-download.sh late data/sound/590.mp3
sh sound-download.sh round data/sound/591.mp3
sh sound-download.sh live data/sound/592.mp3
sh sound-download.sh back data/sound/593.mp3
sh sound-download.sh ball data/sound/594.mp3
sh sound-download.sh circle data/sound/595.mp3
sh sound-download.sh ready data/sound/596.mp3
sh sound-download.sh newspaper data/sound/597.mp3
sh sound-download.sh read data/sound/598.mp3
sh sound-download.sh whole data/sound/599.mp3
sh sound-download.sh noon data/sound/600.mp3
sh sound-download.sh wish data/sound/601.mp3
sh sound-download.sh world data/sound/602.mp3
sh sound-download.sh worry data/sound/603.mp3
sh sound-download.sh together data/sound/604.mp3
sh sound-download.sh clothes data/sound/606.mp3
sh sound-download.sh jeans data/sound/607.mp3
sh sound-download.sh animal data/sound/608.mp3
sh sound-download.sh cow data/sound/609.mp3
sh sound-download.sh clean data/sound/610.mp3
sh sound-download.sh dirty data/sound/611.mp3
sh sound-download.sh cheap data/sound/612.mp3
sh sound-download.sh expensive data/sound/613.mp3
sh sound-download.sh dry data/sound/614.mp3
sh sound-download.sh wet data/sound/615.mp3
sh sound-download.sh cartoon data/sound/616.mp3
sh sound-download.sh draw data/sound/617.mp3
sh sound-download.sh breakfast data/sound/618.mp3
sh sound-download.sh eat data/sound/619.mp3
sh sound-download.sh boil data/sound/620.mp3
sh sound-download.sh borrow data/sound/621.mp3
sh sound-download.sh book data/sound/622.mp3
sh sound-download.sh inside data/sound/623.mp3
sh sound-download.sh outside data/sound/624.mp3
sh sound-download.sh angry data/sound/625.mp3
sh sound-download.sh art data/sound/627.mp3
sh sound-download.sh write data/sound/628.mp3
sh sound-download.sh buy data/sound/629.mp3
sh sound-download.sh brain data/sound/630.mp3
sh sound-download.sh sing data/sound/631.mp3
sh sound-download.sh play data/sound/632.mp3
sh sound-download.sh break data/sound/633.mp3
sh sound-download.sh plant data/sound/634.mp3
sh sound-download.sh bridge data/sound/635.mp3
sh sound-download.sh sorry data/sound/636.mp3
sh sound-download.sh future data/sound/637.mp3
sh sound-download.sh wash data/sound/638.mp3
sh sound-download.sh queen data/sound/639.mp3
sh sound-download.sh card data/sound/640.mp3
sh sound-download.sh ticket data/sound/641.mp3
sh sound-download.sh brand data/sound/642.mp3
sh sound-download.sh game data/sound/643.mp3
sh sound-download.sh breathe data/sound/644.mp3
sh sound-download.sh Thank data/sound/645.mp3
sh sound-download.sh artist data/sound/646.mp3
sh sound-download.sh before data/sound/648.mp3
sh sound-download.sh boring data/sound/649.mp3
sh sound-download.sh safe data/sound/650.mp3
sh sound-download.sh area data/sound/651.mp3
sh sound-download.sh food data/sound/652.mp3
sh sound-download.sh body data/sound/653.mp3
sh sound-download.sh leg data/sound/654.mp3
sh sound-download.sh sun data/sound/655.mp3
sh sound-download.sh away data/sound/656.mp3
sh sound-download.sh baby data/sound/657.mp3
sh sound-download.sh dish data/sound/658.mp3
sh sound-download.sh watch data/sound/660.mp3
sh sound-download.sh visit data/sound/661.mp3
sh sound-download.sh grandparents data/sound/662.mp3
sh sound-download.sh hungry data/sound/663.mp3
sh sound-download.sh full data/sound/664.mp3
sh sound-download.sh thick data/sound/665.mp3
sh sound-download.sh thin data/sound/666.mp3
sh sound-download.sh family data/sound/667.mp3
sh sound-download.sh cousin data/sound/668.mp3
sh sound-download.sh mix data/sound/669.mp3
sh sound-download.sh season data/sound/670.mp3
sh sound-download.sh fall data/sound/671.mp3
sh sound-download.sh sport data/sound/672.mp3
sh sound-download.sh football data/sound/673.mp3
sh sound-download.sh carry data/sound/674.mp3
sh sound-download.sh nurse data/sound/675.mp3
sh sound-download.sh camera data/sound/676.mp3
sh sound-download.sh dead data/sound/677.mp3
sh sound-download.sh business data/sound/678.mp3
sh sound-download.sh butter data/sound/679.mp3
sh sound-download.sh left data/sound/681.mp3
sh sound-download.sh radio data/sound/682.mp3
sh sound-download.sh big data/sound/683.mp3
sh sound-download.sh salt data/sound/684.mp3
sh sound-download.sh listen data/sound/685.mp3
sh sound-download.sh math data/sound/686.mp3
sh sound-download.sh make data/sound/687.mp3
sh sound-download.sh cake data/sound/688.mp3
sh sound-download.sh kite data/sound/689.mp3
sh sound-download.sh fly data/sound/690.mp3
sh sound-download.sh guitar data/sound/691.mp3
sh sound-download.sh room data/sound/692.mp3
sh sound-download.sh invent data/sound/693.mp3
sh sound-download.sh right data/sound/694.mp3
sh sound-download.sh small data/sound/695.mp3
sh sound-download.sh music data/sound/696.mp3
sh sound-download.sh ago data/sound/697.mp3
sh sound-download.sh ahead data/sound/698.mp3
sh sound-download.sh almost data/sound/699.mp3
sh sound-download.sh already data/sound/700.mp3
sh sound-download.sh date data/sound/702.mp3
sh sound-download.sh drive data/sound/703.mp3
sh sound-download.sh brave data/sound/704.mp3
sh sound-download.sh brown data/sound/705.mp3
sh sound-download.sh aunt data/sound/706.mp3
sh sound-download.sh butterfly data/sound/707.mp3
sh sound-download.sh chew data/sound/708.mp3
sh sound-download.sh introduce data/sound/709.mp3
sh sound-download.sh jump data/sound/710.mp3
sh sound-download.sh off data/sound/711.mp3
sh sound-download.sh homework data/sound/712.mp3
sh sound-download.sh surf data/sound/713.mp3
sh sound-download.sh enjoy data/sound/714.mp3
sh sound-download.sh party data/sound/715.mp3
sh sound-download.sh corner data/sound/716.mp3
sh sound-download.sh curly data/sound/717.mp3
sh sound-download.sh curtain data/sound/718.mp3
sh sound-download.sh bright data/sound/719.mp3
sh sound-download.sh deep data/sound/720.mp3
sh sound-download.sh scary data/sound/721.mp3
sh sound-download.sh plane data/sound/723.mp3
sh sound-download.sh character data/sound/724.mp3
sh sound-download.sh strong data/sound/725.mp3
sh sound-download.sh weak data/sound/726.mp3
sh sound-download.sh go data/sound/727.mp3
sh sound-download.sh pilot data/sound/728.mp3
sh sound-download.sh chance data/sound/729.mp3
sh sound-download.sh bake data/sound/730.mp3
sh sound-download.sh congratulate data/sound/731.mp3
sh sound-download.sh fast data/sound/732.mp3
sh sound-download.sh warm data/sound/733.mp3
sh sound-download.sh stretch data/sound/734.mp3
sh sound-download.sh bye data/sound/735.mp3
sh sound-download.sh care data/sound/736.mp3
sh sound-download.sh center data/sound/737.mp3
sh sound-download.sh bring data/sound/738.mp3
sh sound-download.sh church data/sound/739.mp3
sh sound-download.sh check data/sound/740.mp3
sh sound-download.sh stop data/sound/741.mp3
sh sound-download.sh cartoon data/sound/742.mp3
